### ISSUE TITLE
The Celo Dapp Gallery URL is currently not pointing to the Celo Dapp Gallery page

### ISSUE THREAD

**Issue by lopeselio** [figment-networks/datahub-learn#129]
# **The present error:**
Incorrect [URL](https://docs.celo.org/developer-guide/overview/celo-dapp-gallery)
![image](https://user-images.githubusercontent.com/43913734/122218182-cbee3100-cecb-11eb-9341-ca8d4af33b26.png)

## I am updating the link to the Celo Dapp Gallery!
Here is the correct [URL](https://docs.celo.org/developer-guide/celo-dapp-gallery):
![image](https://user-images.githubusercontent.com/43913734/122218390-06f06480-cecc-11eb-84fa-fbfd62408995.png)

I am Linking a Pull Request for the same.

Cheers
**Elio Jordan Lopes**
Celo India Fellow '21

**Comment by yash-sharma1** [comment]
Thanks, @lopeselio for raising the issue and fixing the broken link. Appreciate your contribution :)
Merging your PR now.

**Comment by lopeselio** [comment]
Thanks and cheers! @yash-sharma1
